name: continuous-integration
on: [push]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
      - name: Check Formatting
        run: uv run ruff format --check
      - name: Lint Code
        run: uv run ruff check
      - name: Run Tests
        run: uv run manage.py test
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
